# -*- coding: utf-8 -*-
"""Parkinsons-analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/172tIuAgtt_6iV3DdaJYFjEi57t4yyk_F
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""Reading dataset

"""

import pandas as pd
import matplotlib.pyplot as mp

import seaborn as sb

"""

```
# Import csv file
```

"""

from google.colab import files


uploaded = files.upload()

from io import BytesIO
df = pd.read_csv(BytesIO(uploaded['Parkinsson_disease.csv']))
mp.figure(figsize = (20,10))
dataplot = sb.heatmap(df.corr(), cmap="YlGnBu", annot=True, linewidths=0.5)
  
# displaying heatmap
mp.show()

"""**Removing redundand data **

if covariance>0.75 ; take one of the metrics
[link text](https://)
"""

df.head()

